version: '3'
services:
  web:
    image: nginx:1.17.6-alpine
    ports:
      - "8080:8080"
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
  app:
    build: ./app
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
  db:
    image: mysql:5.7.28
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${PMA_HOST}
      - PMS_USER=${PMS_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    links:
      - db
    ports:
      - "8888:80"
    volumes:
      - /sessions
    depends_on:
      - db
      - web

volumes:
  db-data:
